### ISSUE TITLE
Reconsider `object_type` on `VectorIndex` class

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail-vector-index#18]
As things stand the current design is not fully working.

- https://github.com/wagtail/wagtail-vector-index/blob/main/src/wagtail_vector_index/index/__init__.py#L11 object_type here should be a model class not the index class, right? (edited) 
- https://github.com/wagtail/wagtail-vector-index/blob/main/src/wagtail_vector_index/index/model.py#L69-L79
I think object_type right now as things stand is an instance property of a VectorIndex, but we register a class so we have no info about object_type in the registry.
- or should object_type be a class property? Is a VectorIndex class ever used for multiple object_types?
- or should registry also store the object_type?

Theoretically an answer is that VectorIndex should not have an object_type at all and rely on the results to call appropriate methods. We don't however know yet whether this is the optimal way to do that, especially if there are a lot of rows in the database, and whether we need more suboptimal and restricting design instead.

Right now if you call `get_vector_indexes()`, it won't work. You have to call the `SpecificModel.get_vector_index()` class method to call the `VectorIndex` methods such as `search()` or `query()`.

**Comment by mgax** [comment]
> https://github.com/wagtail/wagtail-vector-index/blob/main/src/wagtail_vector_index/index/__init__.py#L11 object_type here should be a model class not the index class, right? 
> [...]
> Right now if you call `get_vector_indexes()`, it won't work. You have to call the `SpecificModel.get_vector_index()` class method to call the `VectorIndex` methods such as `search()` or `query()`.

I can confirm that the indexes, as returned by `get_vector_indexes()`, can't be used for `search()`. It looks like the `get_vector_indexes` should set the model class as `object_type`, but the model is not readily available in the registry.

**Comment by mgax** [comment]
I've made a PR to fix the immediate issue by hoisting `object_type` to the index class. However, it feels like it's an incomplete solution; the base index class shouldn't care about what kind of documents are getting indexed and whether they map to a particular Python type. Perhaps `object_type` should live in the index classes that work with Django models (`ModelVectorIndex` and `PageVectorIndex`). I'll give it some more thought and maybe write up a proposal to refactor this, and perhaps simplify the registry, to have it store an index instance, instead of the index class.
