### ISSUE TITLE
Add pgvector index for embeddings

### ISSUE THREAD

**Issue by tm-kn** [wagtail/wagtail-vector-index#33]

**Comment by tomusher** [comment]
Just checking what you mean by this issue @tm-kn ?

**Comment by mgax** [comment]
It was about adding a database index to make embedding search faster. It turns out this isn't trivial because the database column doesn't specify a size for the embeddings vector (or something along those lines).

For a bit of context, we were seeing slow (3-4 seconds) search times on Heroku, but it turned out we were fetching all the embeddings into Python and doing the search there. Moving the search in the database reduced query time to ~500ms for ~1300 records (with no index, just doing a table scan) which was good enough.

**Comment by tomusher** [comment]
Ah thank you @mgax - the word 'index' serving double purposes here doesn't do us any favours.

I've written up this issue separately at #49 so we can keep this one closed
